baseurl:
markdown: redcarpet
name: 18F Pages
exclude:
- Gemfile
- Gemfile.lock
- CONTRIBUTING.md
- README.md
- LICENSE.md
- hookshot.js
- fabfile.py
- fabfile.pyc

navigation:
- text: GitHub Repository
  url: https://github.com/18F/pages/
  internal: false
- text: 18F Guides
  url: guides
  internal: true
- text: Guides Template
  url: guides-template
  internal: true

google_analytics_ua: UA-48605964-19

# To use the shared 18F Guides styles when deploying to pages.18f.gov,
# uncomment the following; comment it out during local development:
asset_root: /guides-template

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
