markdown: redcarpet
name: 18F Pages
exclude:
- Gemfile
- Gemfile.lock
- CONTRIBUTING.md
- README.md
- LICENSE.md
- hookshot.js
- fabfile.py
- fabfile.pyc
- gulpfile.js
- node_modules
- package.json

navigation:
- text: Introduction
  url:
  internal: true
  children:
  - text: 18F/pages GitHub Repository
    url: https://github.com/18F/pages/
    internal: false
- text: 18f-pages-server
  url: https://www.npmjs.com/package/18f-pages-server
  internal: false
  children:
  - text: 18F/pages-server GitHub Repository
    url: https://github.com/18F/pages-server/
    internal: false
- text: 18F Guides
  url: guides
  internal: true
  children:
  - text: 18F/guides GitHub Repository
    url: https://github.com/18F/guides/
    internal: false
- text: Guides Template
  url: guides-template
  internal: true
  children:
  - text: 18F/guides-template GitHub Repository
    url: https://github.com/18F/guides-template/
    internal: false

google_analytics_ua: UA-48605964-19

repos:
- name: 18F Pages
  description: 18F Pages GitHub repository
  url: https://github.com/18F/pages

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
